// Каталог нейроголосов Microsoft Edge TTS (общий для Озвучки, Дубляжа и Воронки).
// Чистые данные — без React, чтобы импортировать и в main-процесс (dub/funnel).
export const EDGE_VOICES: Record<string, { value: string; label: string }[]> = {
  ru: [
    { value: 'ru-RU-SvetlanaNeural', label: 'Светлана (ж)' },
    { value: 'ru-RU-DariyaNeural', label: 'Дария (ж)' },
    { value: 'ru-RU-DmitryNeural', label: 'Дмитрий (м)' },
  ],
  en: [
    { value: 'en-US-AriaNeural', label: 'Aria — US (ж)' },
    { value: 'en-US-JennyNeural', label: 'Jenny — US (ж)' },
    { value: 'en-US-MichelleNeural', label: 'Michelle — US (ж)' },
    { value: 'en-US-AnaNeural', label: 'Ana — US, детский (ж)' },
    { value: 'en-US-GuyNeural', label: 'Guy — US (м)' },
    { value: 'en-US-ChristopherNeural', label: 'Christopher — US (м)' },
    { value: 'en-US-EricNeural', label: 'Eric — US (м)' },
    { value: 'en-US-RogerNeural', label: 'Roger — US (м)' },
    { value: 'en-US-SteffanNeural', label: 'Steffan — US (м)' },
    { value: 'en-GB-SoniaNeural', label: 'Sonia — UK (ж)' },
    { value: 'en-GB-LibbyNeural', label: 'Libby — UK (ж)' },
    { value: 'en-GB-MaisieNeural', label: 'Maisie — UK (ж)' },
    { value: 'en-GB-RyanNeural', label: 'Ryan — UK (м)' },
    { value: 'en-GB-ThomasNeural', label: 'Thomas — UK (м)' },
    { value: 'en-AU-NatashaNeural', label: 'Natasha — AU (ж)' },
    { value: 'en-AU-WilliamNeural', label: 'William — AU (м)' },
    { value: 'en-CA-ClaraNeural', label: 'Clara — CA (ж)' },
    { value: 'en-CA-LiamNeural', label: 'Liam — CA (м)' },
  ],
  uk: [
    { value: 'uk-UA-PolinaNeural', label: 'Поліна (ж)' },
    { value: 'uk-UA-OstapNeural', label: 'Остап (м)' },
  ],
  es: [
    { value: 'es-ES-ElviraNeural', label: 'Elvira — ES (ж)' },
    { value: 'es-ES-XimenaNeural', label: 'Ximena — ES (ж)' },
    { value: 'es-ES-AlvaroNeural', label: 'Álvaro — ES (м)' },
    { value: 'es-MX-DaliaNeural', label: 'Dalia — MX (ж)' },
    { value: 'es-MX-RenataNeural', label: 'Renata — MX (ж)' },
    { value: 'es-MX-JorgeNeural', label: 'Jorge — MX (м)' },
    { value: 'es-MX-CecilioNeural', label: 'Cecilio — MX (м)' },
    { value: 'es-AR-ElenaNeural', label: 'Elena — AR (ж)' },
    { value: 'es-AR-TomasNeural', label: 'Tomás — AR (м)' },
    { value: 'es-CO-SalomeNeural', label: 'Salomé — CO (ж)' },
    { value: 'es-CO-GonzaloNeural', label: 'Gonzalo — CO (м)' },
  ],
  de: [
    { value: 'de-DE-KatjaNeural', label: 'Katja (ж)' },
    { value: 'de-DE-AmalaNeural', label: 'Amala (ж)' },
    { value: 'de-DE-SeraphinaNeural', label: 'Seraphina (ж)' },
    { value: 'de-DE-ConradNeural', label: 'Conrad (м)' },
    { value: 'de-DE-KillianNeural', label: 'Killian (м)' },
    { value: 'de-DE-FlorianNeural', label: 'Florian (м)' },
  ],
  fr: [
    { value: 'fr-FR-DeniseNeural', label: 'Denise — FR (ж)' },
    { value: 'fr-FR-EloiseNeural', label: 'Eloise — FR (ж)' },
    { value: 'fr-FR-VivienneNeural', label: 'Vivienne — FR (ж)' },
    { value: 'fr-FR-HenriNeural', label: 'Henri — FR (м)' },
    { value: 'fr-CA-SylvieNeural', label: 'Sylvie — CA (ж)' },
    { value: 'fr-CA-AntoineNeural', label: 'Antoine — CA (м)' },
    { value: 'fr-CA-JeanNeural', label: 'Jean — CA (м)' },
    { value: 'fr-CH-ArianeNeural', label: 'Ariane — CH (ж)' },
    { value: 'fr-CH-FabriceNeural', label: 'Fabrice — CH (м)' },
    { value: 'fr-BE-CharlineNeural', label: 'Charline — BE (ж)' },
    { value: 'fr-BE-GerardNeural', label: 'Gerard — BE (м)' },
  ],
  it: [
    { value: 'it-IT-ElsaNeural', label: 'Elsa (ж)' },
    { value: 'it-IT-IsabellaNeural', label: 'Isabella (ж)' },
    { value: 'it-IT-FabiolaNeural', label: 'Fabiola (ж)' },
    { value: 'it-IT-DiegoNeural', label: 'Diego (м)' },
    { value: 'it-IT-GiuseppeNeural', label: 'Giuseppe (м)' },
    { value: 'it-IT-BenignoNeural', label: 'Benigno (м)' },
  ],
  pt: [
    { value: 'pt-BR-FranciscaNeural', label: 'Francisca — BR (ж)' },
    { value: 'pt-BR-BrendaNeural', label: 'Brenda — BR (ж)' },
    { value: 'pt-BR-GiovannaNeural', label: 'Giovanna — BR (ж)' },
    { value: 'pt-BR-LeilaNeural', label: 'Leila — BR (ж)' },
    { value: 'pt-BR-LeticiaNeural', label: 'Letícia — BR (ж)' },
    { value: 'pt-BR-ManuelaNeural', label: 'Manuela — BR (ж)' },
    { value: 'pt-BR-YaraNeural', label: 'Yara — BR (ж)' },
    { value: 'pt-BR-AntonioNeural', label: 'Antônio — BR (м)' },
    { value: 'pt-BR-DonatoNeural', label: 'Donato — BR (м)' },
    { value: 'pt-BR-FabioNeural', label: 'Fábio — BR (м)' },
    { value: 'pt-BR-HumbertoNeural', label: 'Humberto — BR (м)' },
    { value: 'pt-BR-JulioNeural', label: 'Júlio — BR (м)' },
    { value: 'pt-BR-NicolauNeural', label: 'Nicolau — BR (м)' },
    { value: 'pt-BR-ValerioNeural', label: 'Valério — BR (м)' },
    { value: 'pt-PT-RaquelNeural', label: 'Raquel — PT (ж)' },
    { value: 'pt-PT-FernandaNeural', label: 'Fernanda — PT (ж)' },
    { value: 'pt-PT-DuarteNeural', label: 'Duarte — PT (м)' },
  ],
  pl: [
    { value: 'pl-PL-ZofiaNeural', label: 'Zofia (ж)' },
    { value: 'pl-PL-MarekNeural', label: 'Marek (м)' },
  ],
  tr: [
    { value: 'tr-TR-EmelNeural', label: 'Emel (ж)' },
    { value: 'tr-TR-AhmetNeural', label: 'Ahmet (м)' },
  ],
  ar: [
    { value: 'ar-SA-ZariyahNeural', label: 'Zariyah (ж)' },
    { value: 'ar-SA-HamedNeural', label: 'Hamed (м)' },
  ],
  hi: [
    { value: 'hi-IN-SwaraNeural', label: 'Swara (ж)' },
    { value: 'hi-IN-MadhurNeural', label: 'Madhur (м)' },
  ],
  ja: [
    { value: 'ja-JP-NanamiNeural', label: 'Nanami (ж)' },
    { value: 'ja-JP-MayuNeural', label: 'Mayu (ж)' },
    { value: 'ja-JP-KeitaNeural', label: 'Keita (м)' },
    { value: 'ja-JP-DaichiNeural', label: 'Daichi (м)' },
  ],
  ko: [
    { value: 'ko-KR-SunHiNeural', label: 'SunHi (ж)' },
    { value: 'ko-KR-JiMinNeural', label: 'JiMin (ж)' },
    { value: 'ko-KR-InJoonNeural', label: 'InJoon (м)' },
    { value: 'ko-KR-HyunsuNeural', label: 'Hyunsu (м)' },
  ],
  zh: [
    { value: 'zh-CN-XiaoxiaoNeural', label: 'Xiaoxiao (ж)' },
    { value: 'zh-CN-XiaoyiNeural', label: 'Xiaoyi (ж)' },
    { value: 'zh-CN-YunxiNeural', label: 'Yunxi (м)' },
    { value: 'zh-CN-YunyangNeural', label: 'Yunyang (м)' },
    { value: 'zh-CN-YunjianNeural', label: 'Yunjian (м)' },
  ],
};

// Случайный голос для языка (для «разнообразия» в Воронке). Пусто, если языка нет.
export function randomVoice(lang: string): string {
  const list = EDGE_VOICES[lang];
  if (!list || !list.length) return '';
  return list[Math.floor(Math.random() * list.length)].value;
}
